<?php

# this is autogenerated file, do not edit

return array (
  'c_calendar' => 
  array (
    'empty_a' => 
    array (
      0 => 1,
      1 => 
      array (
        0 => 1,
      ),
      2 => 
      array (
      ),
      3 => 
      array (
      ),
    ),
  ),
);

